### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by toanpt74** [Gaupy/linear-workflows#1]
Thank you very much, but I want to ask you about the struct of workflow in the xml file, can you help me? example in the Montage_25.xml file, I see the output data size in the job ID00000 is 4167312, but I don't know 4167312MB or 4167312GB or 4167312B, can you help me???
thanks

**Comment by Gaupy** [comment]
I would assume it is in Bytes, however I have not been able to find the answer on the Pegasus website (http://pegasus.isi.edu/), it seems they have modified their DAG format. I am sorry I cannot be of more help.

**Comment by toanpt74** [comment]
Thank you very much
